name: Sync to gcs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0pu
        with:
          service_account_key: ${GCP_CREDENTIAL_FILE}
      - run: gcloud auth configure-docker
      - run: |
          gsutil rsync -r ${SOURCE_PATH} ${DESTINATION_GCS_PATH}
          echo "Sync completed"
