name: push-to-gcs-actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIAL_PATH }}
      - run: gcloud auth configure-docker
      - run: ./sync.sh
